// <copyright file="UnitTestBase.cs" company="Microsoft">
// Copyright (c) 2020 All Rights Reserved
// </copyright>
// <author></author>
// <date>3/11/2020</date>
// <summary>Implements the CommonHelper</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace PPTemplateALMPlugins.UnitTest
{
    using System;
    using System.Activities;
    using System.Collections.Generic;
    using System.Fakes;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Microsoft.Xrm.Sdk;
    using Microsoft.Xrm.Sdk.Fakes;
    using Microsoft.Xrm.Sdk.Workflow;
    using Microsoft.Xrm.Sdk.Workflow.Fakes;
    using Microsoft.Xrm.Tooling.Connector;
    using Microsoft.Xrm.Tooling.Connector.Fakes;

    [TestClass]
    public class UnitTestBase
    {

        public ShimCrmServiceClient ServiceClient { get; set; }

        public StubIOrganizationService Service { get; set; }

        public StubIPluginExecutionContext PluginExecutionContext { get; set; }

        public StubIOrganizationServiceFactory Factory { get; set; }

        public StubIServiceProvider ServiceProvider { get; set; }

        public StubITracingService TracingService { get; set; }

        public StubIWorkflowContext WorkflowContext { get; set; }

        public StubIServiceEndpointNotificationService ServiceEndpointNotificationService { get; set; }


        [TestInitialize]
        public void Init()
        {
            //// this.ServiceClient = new ShimCrmServiceClient();

            this.Service = new StubIOrganizationService();

            this.PluginExecutionContext = new StubIPluginExecutionContext();

            this.WorkflowContext = new StubIWorkflowContext();

            this.Factory = new StubIOrganizationServiceFactory
            {
                CreateOrganizationServiceNullableOfGuid = id => Service
            };

            this.TracingService = new StubITracingService();

            this.ServiceEndpointNotificationService = new StubIServiceEndpointNotificationService();

            this.ServiceProvider = new StubIServiceProvider
            {
                GetServiceType = t =>
                {
                    if (t == typeof(IWorkflowContext))
                    {
                        return WorkflowContext;
                    }

                    if (t == typeof(IPluginExecutionContext))
                    {
                        return PluginExecutionContext;
                    }

                    if (t == typeof(ITracingService))
                    {
                        return TracingService;
                    }

                    if (t == typeof(IOrganizationServiceFactory))
                    {
                        return Factory;
                    }

                    if (t == typeof(IServiceEndpointNotificationService))
                    {
                        return ServiceEndpointNotificationService;
                    }

                    return null;
                }
            };

            this.WorkflowContext.UserIdGet = () =>
            {
                return Guid.NewGuid();
            };
            this.WorkflowContext.CorrelationIdGet = () =>
            {
                return Guid.NewGuid();
            };
            this.WorkflowContext.InitiatingUserIdGet = () =>
            {
                return Guid.NewGuid();
            };
        }

        [TestCleanup]
        public void Cleanup()
        {
            this.Service = null;

            this.PluginExecutionContext = null;

            this.Factory = null;

            this.ServiceProvider = null;

            this.WorkflowContext = null;
        }

        /// <summary>
        /// Executes the workflow.
        /// </summary>
        /// <param name="workflow">The workflow.</param>
        /// <param name="inputs">The inputs.</param>
        /// <returns>Execution result</returns>
        public IDictionary<string, object> ExecuteWorkflow(Activity workflow, IDictionary<string, object> inputs)
        {
            var invoker = new WorkflowInvoker(workflow);
            invoker.Extensions.Add<ITracingService>(() => this.TracingService);
            invoker.Extensions.Add<IWorkflowContext>(() => this.WorkflowContext);
            invoker.Extensions.Add<IOrganizationServiceFactory>(() => this.Factory);

            if (inputs != null)
            {
                return invoker.Invoke(inputs);
            }
            else
            {
                return invoker.Invoke();
            }
        }

        /// <summary>
        /// Executes the workflow.
        /// </summary>
        /// <param name="workflow">The workflow.</param>
        /// <returns>Execution result</returns>
        public IDictionary<string, object> ExecuteWorkflow(Activity workflow)
        {
            return this.ExecuteWorkflow(workflow, null);
        }
    }
}
